// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/app_service.proto

package app_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_app_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_app_service_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_app_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_app_service_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRequest) Reset() {
	*x = SwitchRequest{}
	mi := &file_proto_app_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRequest) ProtoMessage() {}

func (x *SwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRequest.ProtoReflect.Descriptor instead.
func (*SwitchRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_service_proto_rawDescGZIP(), []int{2}
}

func (x *SwitchRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_proto_app_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_service_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_app_service_proto protoreflect.FileDescriptor

const file_proto_app_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/app_service.proto\x12\vapp_service\"\a\n" +
	"\x05Empty\"<\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\rSwitchRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"+\n" +
	"\x0fRollbackRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2\xb5\x02\n" +
	"\n" +
	"AppService\x126\n" +
	"\vStopService\x12\x12.app_service.Empty\x1a\x13.app_service.Status\x127\n" +
	"\fStartService\x12\x12.app_service.Empty\x1a\x13.app_service.Status\x125\n" +
	"\n" +
	"RestartApp\x12\x12.app_service.Empty\x1a\x13.app_service.Status\x12@\n" +
	"\rSwitchCurrent\x12\x1a.app_service.SwitchRequest\x1a\x13.app_service.Status\x12=\n" +
	"\bRollback\x12\x1c.app_service.RollbackRequest\x1a\x13.app_service.StatusB\x0fZ\r./app_serviceb\x06proto3"

var (
	file_proto_app_service_proto_rawDescOnce sync.Once
	file_proto_app_service_proto_rawDescData []byte
)

func file_proto_app_service_proto_rawDescGZIP() []byte {
	file_proto_app_service_proto_rawDescOnce.Do(func() {
		file_proto_app_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_service_proto_rawDesc), len(file_proto_app_service_proto_rawDesc)))
	})
	return file_proto_app_service_proto_rawDescData
}

var file_proto_app_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_app_service_proto_goTypes = []any{
	(*Empty)(nil),           // 0: app_service.Empty
	(*Status)(nil),          // 1: app_service.Status
	(*SwitchRequest)(nil),   // 2: app_service.SwitchRequest
	(*RollbackRequest)(nil), // 3: app_service.RollbackRequest
}
var file_proto_app_service_proto_depIdxs = []int32{
	0, // 0: app_service.AppService.StopService:input_type -> app_service.Empty
	0, // 1: app_service.AppService.StartService:input_type -> app_service.Empty
	0, // 2: app_service.AppService.RestartApp:input_type -> app_service.Empty
	2, // 3: app_service.AppService.SwitchCurrent:input_type -> app_service.SwitchRequest
	3, // 4: app_service.AppService.Rollback:input_type -> app_service.RollbackRequest
	1, // 5: app_service.AppService.StopService:output_type -> app_service.Status
	1, // 6: app_service.AppService.StartService:output_type -> app_service.Status
	1, // 7: app_service.AppService.RestartApp:output_type -> app_service.Status
	1, // 8: app_service.AppService.SwitchCurrent:output_type -> app_service.Status
	1, // 9: app_service.AppService.Rollback:output_type -> app_service.Status
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_app_service_proto_init() }
func file_proto_app_service_proto_init() {
	if File_proto_app_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_service_proto_rawDesc), len(file_proto_app_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_service_proto_goTypes,
		DependencyIndexes: file_proto_app_service_proto_depIdxs,
		MessageInfos:      file_proto_app_service_proto_msgTypes,
	}.Build()
	File_proto_app_service_proto = out.File
	file_proto_app_service_proto_goTypes = nil
	file_proto_app_service_proto_depIdxs = nil
}
