// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package db

import (
	"context"
	"database/sql"
)

const addUserToChannel = `-- name: AddUserToChannel :one
INSERT INTO channel_members (channel_id, user_id)
VALUES ($1, $2)
RETURNING id, channel_id, user_id, joined_at, left_at
`

type AddUserToChannelParams struct {
	ChannelID int64
	UserID    int64
}

// -------------------------------
// 7. Add user to channel
// -------------------------------
func (q *Queries) AddUserToChannel(ctx context.Context, arg AddUserToChannelParams) (ChannelMember, error) {
	row := q.db.QueryRowContext(ctx, addUserToChannel, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description,  owner_id, thumbnail, banner, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, name, description, thumbnail, banner, owner_id, created_at, updated_at, deleted_at
`

type CreateChannelParams struct {
	Name        string
	Description string
	OwnerID     int64
	Thumbnail   string
	Banner      string
}

// -------------------------------
// 1. Create a channel
// -------------------------------
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Thumbnail,
		arg.Banner,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const followChannel = `-- name: FollowChannel :one
INSERT INTO channel_followers (channel_id, user_id)
VALUES ($1, $2)
RETURNING id, channel_id, user_id, followed_at, unfollowed_at
`

type FollowChannelParams struct {
	ChannelID int64
	UserID    int64
}

// -------------------------------
// 9. Follow a channel
// -------------------------------
func (q *Queries) FollowChannel(ctx context.Context, arg FollowChannelParams) (ChannelFollower, error) {
	row := q.db.QueryRowContext(ctx, followChannel, arg.ChannelID, arg.UserID)
	var i ChannelFollower
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.FollowedAt,
		&i.UnfollowedAt,
	)
	return i, err
}

const getAllChannels = `-- name: GetAllChannels :many
SELECT 
    c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.created_at, c.updated_at, c.deleted_at,
    (c.owner_id = $1) AS is_owner,
    EXISTS (
        SELECT 1 
        FROM channel_members cm 
        WHERE cm.channel_id = c.id 
          AND cm.user_id = $1 
          AND cm.left_at IS NULL
    ) AS is_member,
    EXISTS (
        SELECT 1 
        FROM channel_followers cf 
        WHERE cf.channel_id = c.id 
          AND cf.user_id = $1 
          AND cf.unfollowed_at IS NULL
    ) AS is_follower
FROM channels c
WHERE c.deleted_at IS NULL
LIMIT $2 OFFSET $3
`

type GetAllChannelsParams struct {
	OwnerID int64
	Limit   int64
	Offset  int64
}

type GetAllChannelsRow struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Banner      string
	OwnerID     int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	IsOwner     bool
	IsMember    bool
	IsFollower  bool
}

// -------------------------------
// 9. Get All Channels
// -------------------------------
func (q *Queries) GetAllChannels(ctx context.Context, arg GetAllChannelsParams) ([]GetAllChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllChannels, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChannelsRow
	for rows.Next() {
		var i GetAllChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsOwner,
			&i.IsMember,
			&i.IsFollower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one
SELECT 
    c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.created_at, c.updated_at, c.deleted_at,
    (c.owner_id = $1) AS is_owner,
    EXISTS (
        SELECT 1 
        FROM channel_members cm 
        WHERE cm.channel_id = c.id 
          AND cm.user_id = $1 
          AND cm.left_at IS NULL
    ) AS is_member,
    EXISTS (
        SELECT 1 
        FROM channel_followers cf 
        WHERE cf.channel_id = c.id 
          AND cf.user_id = $1 
          AND cf.unfollowed_at IS NULL
    ) AS is_follower
FROM channels c
WHERE c.id = $2 AND c.deleted_at IS NULL
`

type GetChannelParams struct {
	OwnerID int64
	ID      int64
}

type GetChannelRow struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Banner      string
	OwnerID     int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	IsOwner     bool
	IsMember    bool
	IsFollower  bool
}

// -------------------------------
// 10. Get Channel by ID with Membership and Follower Status
// -------------------------------
func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (GetChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getChannel, arg.OwnerID, arg.ID)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsOwner,
		&i.IsMember,
		&i.IsFollower,
	)
	return i, err
}

const getChannelsForUser = `-- name: GetChannelsForUser :many
SELECT c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.created_at, c.updated_at, c.deleted_at
FROM channel_members cm
JOIN channels c ON cm.channel_id = c.id
WHERE cm.user_id = $1
  AND cm.left_at IS NULL
`

// -------------------------------
// 5. Get channels a user is a member of
// -------------------------------
func (q *Queries) GetChannelsForUser(ctx context.Context, userID int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowedChannelsForUser = `-- name: GetFollowedChannelsForUser :many
SELECT c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.created_at, c.updated_at, c.deleted_at
FROM channel_followers cf
JOIN channels c ON cf.channel_id = c.id
WHERE cf.user_id = $1
  AND cf.unfollowed_at IS NULL
`

// -------------------------------
// 6. Get channels a user follows
// -------------------------------
func (q *Queries) GetFollowedChannelsForUser(ctx context.Context, userID int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, description, thumbnail, banner, owner_id, created_at, updated_at, deleted_at
FROM channels
WHERE deleted_at IS NULL
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListChannelsParams struct {
	Limit  int64
	Offset int64
}

// -------------------------------
// 4. List all channels
// -------------------------------
func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannel = `-- name: RemoveChannel :one
UPDATE channels
SET deleted_at = NOW()
WHERE id = $1
RETURNING id, name, description, thumbnail, banner, owner_id, created_at, updated_at, deleted_at
`

// -------------------------------
// 3. Remove a channel (soft delete)
// -------------------------------
func (q *Queries) RemoveChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, removeChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const removeUserFromChannel = `-- name: RemoveUserFromChannel :one
UPDATE channel_members
SET left_at = NOW()
WHERE channel_id = $1 AND user_id = $2
RETURNING id, channel_id, user_id, joined_at, left_at
`

type RemoveUserFromChannelParams struct {
	ChannelID int64
	UserID    int64
}

// -------------------------------
// 8. Remove user from channel (leave)
// -------------------------------
func (q *Queries) RemoveUserFromChannel(ctx context.Context, arg RemoveUserFromChannelParams) (ChannelMember, error) {
	row := q.db.QueryRowContext(ctx, removeUserFromChannel, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const unfollowChannel = `-- name: UnfollowChannel :one
UPDATE channel_followers
SET unfollowed_at = NOW()
WHERE channel_id = $1 AND user_id = $2
RETURNING id, channel_id, user_id, followed_at, unfollowed_at
`

type UnfollowChannelParams struct {
	ChannelID int64
	UserID    int64
}

// -------------------------------
// 10. Unfollow a channel
// -------------------------------
func (q *Queries) UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) (ChannelFollower, error) {
	row := q.db.QueryRowContext(ctx, unfollowChannel, arg.ChannelID, arg.UserID)
	var i ChannelFollower
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.FollowedAt,
		&i.UnfollowedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, description, thumbnail, banner, owner_id, created_at, updated_at, deleted_at
`

type UpdateChannelParams struct {
	Name        string
	Description string
	ID          int64
}

// -------------------------------
// 2. Update channel
// -------------------------------
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel, arg.Name, arg.Description, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
