// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package db

import (
	"context"
	"database/sql"
)

const addUserToChannel = `-- name: AddUserToChannel :one
INSERT INTO channel_members (channel_id, persona_id, status)
VALUES ($1, $2, $3)
RETURNING id, channel_id, persona_id, joined_at, left_at, status
`

type AddUserToChannelParams struct {
	ChannelID int64
	PersonaID int64
	Status    ChannelMembershipStatusEnum
}

// -------------------------------
// 7. Add user to channel
// -------------------------------
func (q *Queries) AddUserToChannel(ctx context.Context, arg AddUserToChannelParams) (ChannelMember, error) {
	row := q.db.QueryRowContext(ctx, addUserToChannel, arg.ChannelID, arg.PersonaID, arg.Status)
	var i ChannelMember
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PersonaID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Status,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description,  owner_id, thumbnail, banner, visibility, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, name, description, thumbnail, banner, owner_id, visibility, created_at, updated_at, deleted_at
`

type CreateChannelParams struct {
	Name        string
	Description string
	OwnerID     int64
	Thumbnail   string
	Banner      string
	Visibility  ChannelVisibilityEnum
}

// -------------------------------
// 1. Create a channel
// -------------------------------
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Thumbnail,
		arg.Banner,
		arg.Visibility,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const followChannel = `-- name: FollowChannel :one
INSERT INTO channel_followers (channel_id, persona_id)
VALUES ($1, $2)
RETURNING id, channel_id, persona_id, followed_at, unfollowed_at
`

type FollowChannelParams struct {
	ChannelID int64
	PersonaID int64
}

// -------------------------------
// 9. Follow a channel
// -------------------------------
func (q *Queries) FollowChannel(ctx context.Context, arg FollowChannelParams) (ChannelFollower, error) {
	row := q.db.QueryRowContext(ctx, followChannel, arg.ChannelID, arg.PersonaID)
	var i ChannelFollower
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PersonaID,
		&i.FollowedAt,
		&i.UnfollowedAt,
	)
	return i, err
}

const getAllChannels = `-- name: GetAllChannels :many
SELECT 
    c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.visibility, c.created_at, c.updated_at, c.deleted_at,
    (c.owner_id = $1) AS is_owner,
    EXISTS (
        SELECT 1 
        FROM channel_members cm 
        WHERE cm.channel_id = c.id 
          AND cm.persona_id = $1 
          AND cm.left_at IS NULL AND cm.status = 'active'
    ) AS is_member,
    EXISTS (
        SELECT 1 
        FROM channel_members cm 
        WHERE cm.channel_id = c.id 
          AND cm.persona_id = $1 
          AND cm.left_at IS NULL AND cm.status = 'pending'
    ) AS is_pending,
    EXISTS (
        SELECT 1 
        FROM channel_followers cf 
        WHERE cf.channel_id = c.id 
          AND cf.persona_id = $1 
          AND cf.unfollowed_at IS NULL
    ) AS is_follower
FROM channels c
WHERE c.deleted_at IS NULL
LIMIT $2 OFFSET $3
`

type GetAllChannelsParams struct {
	OwnerID int64
	Limit   int64
	Offset  int64
}

type GetAllChannelsRow struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Banner      string
	OwnerID     int64
	Visibility  ChannelVisibilityEnum
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	IsOwner     bool
	IsMember    bool
	IsPending   bool
	IsFollower  bool
}

// -------------------------------
// 9. Get All Channels
// -------------------------------
func (q *Queries) GetAllChannels(ctx context.Context, arg GetAllChannelsParams) ([]GetAllChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllChannels, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChannelsRow
	for rows.Next() {
		var i GetAllChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsOwner,
			&i.IsMember,
			&i.IsPending,
			&i.IsFollower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one
SELECT 
    c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.visibility, c.created_at, c.updated_at, c.deleted_at,
    (c.owner_id = $1) AS is_owner,
    EXISTS (
        SELECT 1 
        FROM channel_members cm 
        WHERE cm.channel_id = c.id 
          AND cm.persona_id = $1 
          AND cm.left_at IS NULL AND cm.status = 'active'
    ) AS is_member,
    EXISTS (
        SELECT 1 
        FROM channel_members cm 
        WHERE cm.channel_id = c.id 
          AND cm.persona_id = $1 
          AND cm.left_at IS NULL AND cm.status = 'pending'
    ) AS is_pending,
    EXISTS (
        SELECT 1 
        FROM channel_followers cf 
        WHERE cf.channel_id = c.id 
          AND cf.persona_id = $1 
          AND cf.unfollowed_at IS NULL
    ) AS is_follower
FROM channels c
WHERE c.id = $2 AND c.deleted_at IS NULL
`

type GetChannelParams struct {
	OwnerID int64
	ID      int64
}

type GetChannelRow struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Banner      string
	OwnerID     int64
	Visibility  ChannelVisibilityEnum
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	IsOwner     bool
	IsMember    bool
	IsPending   bool
	IsFollower  bool
}

// -------------------------------
// 10. Get Channel by ID with Membership and Follower Status
// -------------------------------
func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (GetChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getChannel, arg.OwnerID, arg.ID)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsOwner,
		&i.IsMember,
		&i.IsPending,
		&i.IsFollower,
	)
	return i, err
}

const getChannelAccess = `-- name: GetChannelAccess :one
SELECT
    c.id,
    c.visibility,
    (c.owner_id = $1::bigint) AS is_owner,
    EXISTS (
        SELECT 1
        FROM channel_members cm
        WHERE cm.channel_id = c.id
          AND cm.persona_id = $1::bigint
          AND cm.left_at IS NULL AND cm.status = 'active'
    ) AS is_member,
    EXISTS (
        SELECT 1
        FROM channel_members cm
        WHERE cm.channel_id = c.id
          AND cm.persona_id = $1::bigint
          AND cm.left_at IS NULL AND cm.status = 'pending'
    ) AS is_pending,
    (
        c.owner_id = $1::bigint
        OR EXISTS (
            SELECT 1
            FROM channel_roles cr
            JOIN roles r ON r.id = cr.role_id
            WHERE cr.channel_id = c.id
              AND cr.persona_id = $1::bigint
              AND cr.deleted_at IS NULL
              AND r.name IN ('moderator', 'Administrator')
        )
        OR EXISTS (
            SELECT 1
            FROM personas p
            JOIN user_roles ur ON ur.user_id = p.user_id AND ur.deleted_at IS NULL
            JOIN roles r ON r.id = ur.role_id
            WHERE p.id = $1::bigint
              AND r.name = 'Administrator'
        )
    )::boolean AS can_moderate
FROM channels c
WHERE c.id = $2::bigint AND c.deleted_at IS NULL
`

type GetChannelAccessParams struct {
	PersonaID int64
	ChannelID int64
}

type GetChannelAccessRow struct {
	ID          int64
	Visibility  ChannelVisibilityEnum
	IsOwner     bool
	IsMember    bool
	IsPending   bool
	CanModerate bool
}

// -------------------------------
// 11. What a persona may do in a channel
// -------------------------------
// A missing row (sql.ErrNoRows) means the channel does not exist or is deleted.
// can_moderate: channel owner, a channel moderator/Administrator, or a global Administrator.
func (q *Queries) GetChannelAccess(ctx context.Context, arg GetChannelAccessParams) (GetChannelAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getChannelAccess, arg.PersonaID, arg.ChannelID)
	var i GetChannelAccessRow
	err := row.Scan(
		&i.ID,
		&i.Visibility,
		&i.IsOwner,
		&i.IsMember,
		&i.IsPending,
		&i.CanModerate,
	)
	return i, err
}

const getChannelsForUser = `-- name: GetChannelsForUser :many
SELECT c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.visibility, c.created_at, c.updated_at, c.deleted_at
FROM channel_members cm
JOIN channels c ON cm.channel_id = c.id
WHERE cm.persona_id = $1
  AND cm.left_at IS NULL AND cm.status = 'active'
`

// -------------------------------
// 5. Get channels a user is a member of
// -------------------------------
func (q *Queries) GetChannelsForUser(ctx context.Context, personaID int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getChannelsForUser, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowedChannelsForUser = `-- name: GetFollowedChannelsForUser :many
SELECT c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.visibility, c.created_at, c.updated_at, c.deleted_at
FROM channel_followers cf
JOIN channels c ON cf.channel_id = c.id
WHERE cf.persona_id = $1
  AND cf.unfollowed_at IS NULL
`

// -------------------------------
// 6. Get channels a user follows
// -------------------------------
func (q *Queries) GetFollowedChannelsForUser(ctx context.Context, personaID int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedChannelsForUser, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT
    cm.persona_id,
    cm.joined_at,
    p.name,
    p.first_name,
    p.last_name,
    p.thumbnail,
    (c.owner_id = cm.persona_id)::boolean AS is_owner,
    EXISTS (
        SELECT 1
        FROM channel_roles cr
        JOIN roles r ON r.id = cr.role_id
        WHERE cr.channel_id = cm.channel_id
          AND cr.persona_id = cm.persona_id
          AND cr.deleted_at IS NULL
          AND r.name IN ('moderator', 'Administrator')
    )::boolean AS is_moderator
FROM channel_members cm
JOIN channels c ON c.id = cm.channel_id
JOIN personas p ON p.id = cm.persona_id
WHERE cm.channel_id = $1
  AND cm.left_at IS NULL
  AND cm.status = 'active'
ORDER BY (c.owner_id = cm.persona_id) DESC, cm.joined_at
`

type ListChannelMembersRow struct {
	PersonaID   int64
	JoinedAt    sql.NullTime
	Name        string
	FirstName   string
	LastName    string
	Thumbnail   sql.NullString
	IsOwner     bool
	IsModerator bool
}

// -------------------------------
// 14. List active members (moderators only)
// -------------------------------
func (q *Queries) ListChannelMembers(ctx context.Context, channelID int64) ([]ListChannelMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelMembersRow
	for rows.Next() {
		var i ListChannelMembersRow
		if err := rows.Scan(
			&i.PersonaID,
			&i.JoinedAt,
			&i.Name,
			&i.FirstName,
			&i.LastName,
			&i.Thumbnail,
			&i.IsOwner,
			&i.IsModerator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, description, thumbnail, banner, owner_id, visibility, created_at, updated_at, deleted_at
FROM channels
WHERE deleted_at IS NULL
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListChannelsParams struct {
	Limit  int64
	Offset int64
}

// -------------------------------
// 4. List all channels
// -------------------------------
func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJoinRequests = `-- name: ListPendingJoinRequests :many
SELECT
    cm.persona_id,
    cm.joined_at AS requested_at,
    p.name,
    p.first_name,
    p.last_name,
    p.thumbnail
FROM channel_members cm
JOIN personas p ON p.id = cm.persona_id
WHERE cm.channel_id = $1
  AND cm.left_at IS NULL
  AND cm.status = 'pending'
ORDER BY cm.joined_at
`

type ListPendingJoinRequestsRow struct {
	PersonaID   int64
	RequestedAt sql.NullTime
	Name        string
	FirstName   string
	LastName    string
	Thumbnail   sql.NullString
}

// -------------------------------
// 12. Pending join requests for a channel
// -------------------------------
func (q *Queries) ListPendingJoinRequests(ctx context.Context, channelID int64) ([]ListPendingJoinRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJoinRequests, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingJoinRequestsRow
	for rows.Next() {
		var i ListPendingJoinRequestsRow
		if err := rows.Scan(
			&i.PersonaID,
			&i.RequestedAt,
			&i.Name,
			&i.FirstName,
			&i.LastName,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannel = `-- name: RemoveChannel :one
UPDATE channels
SET deleted_at = NOW()
WHERE id = $1
RETURNING id, name, description, thumbnail, banner, owner_id, visibility, created_at, updated_at, deleted_at
`

// -------------------------------
// 3. Remove a channel (soft delete)
// -------------------------------
func (q *Queries) RemoveChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, removeChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const removeUserFromChannel = `-- name: RemoveUserFromChannel :one
UPDATE channel_members
SET left_at = NOW()
WHERE channel_id = $1 AND persona_id = $2 AND left_at IS NULL
RETURNING id, channel_id, persona_id, joined_at, left_at, status
`

type RemoveUserFromChannelParams struct {
	ChannelID int64
	PersonaID int64
}

// -------------------------------
// 8. Remove user from channel (leave)
// -------------------------------
// Ends the current membership or pending request; earlier memberships keep
// their left_at.
func (q *Queries) RemoveUserFromChannel(ctx context.Context, arg RemoveUserFromChannelParams) (ChannelMember, error) {
	row := q.db.QueryRowContext(ctx, removeUserFromChannel, arg.ChannelID, arg.PersonaID)
	var i ChannelMember
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PersonaID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Status,
	)
	return i, err
}

const resolveJoinRequest = `-- name: ResolveJoinRequest :one
UPDATE channel_members
SET status = $1::channel_membership_status_enum
WHERE channel_id = $2::bigint
  AND persona_id = $3::bigint
  AND left_at IS NULL
  AND status = 'pending'
RETURNING id, channel_id, persona_id, joined_at, left_at, status
`

type ResolveJoinRequestParams struct {
	Status    ChannelMembershipStatusEnum
	ChannelID int64
	PersonaID int64
}

// -------------------------------
// 13. Approve or reject a pending join request
// -------------------------------
func (q *Queries) ResolveJoinRequest(ctx context.Context, arg ResolveJoinRequestParams) (ChannelMember, error) {
	row := q.db.QueryRowContext(ctx, resolveJoinRequest, arg.Status, arg.ChannelID, arg.PersonaID)
	var i ChannelMember
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PersonaID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Status,
	)
	return i, err
}

const unfollowChannel = `-- name: UnfollowChannel :one
UPDATE channel_followers
SET unfollowed_at = NOW()
WHERE channel_id = $1 AND persona_id = $2
RETURNING id, channel_id, persona_id, followed_at, unfollowed_at
`

type UnfollowChannelParams struct {
	ChannelID int64
	PersonaID int64
}

// -------------------------------
// 10. Unfollow a channel
// -------------------------------
func (q *Queries) UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) (ChannelFollower, error) {
	row := q.db.QueryRowContext(ctx, unfollowChannel, arg.ChannelID, arg.PersonaID)
	var i ChannelFollower
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PersonaID,
		&i.FollowedAt,
		&i.UnfollowedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, description, thumbnail, banner, owner_id, visibility, created_at, updated_at, deleted_at
`

type UpdateChannelParams struct {
	Name        string
	Description string
	ID          int64
}

// -------------------------------
// 2. Update channel
// -------------------------------
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel, arg.Name, arg.Description, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Banner,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
