// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name,
    action,
    target_id,
    target_type,
    owner,
    owner_id,
    actor_id,
    object_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, action, target_id, target_type, owner, owner_id, actor_id, created_at, updated_at, deleted_at, object_id
`

type CreateEventParams struct {
	Name       EventEnum
	Action     EventActionEnum
	TargetID   string
	TargetType EventTargetTypeEnum
	Owner      OwnerEnum
	OwnerID    int64
	ActorID    int64
	ObjectID   string
}

// -------------------------------
// 1. Create a new Event
// -------------------------------
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.Action,
		arg.TargetID,
		arg.TargetType,
		arg.Owner,
		arg.OwnerID,
		arg.ActorID,
		arg.ObjectID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Action,
		&i.TargetID,
		&i.TargetType,
		&i.Owner,
		&i.OwnerID,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ObjectID,
	)
	return i, err
}

const getLikedTargets = `-- name: GetLikedTargets :many
SELECT DISTINCT target_id
FROM events
WHERE actor_id = $1::bigint
  AND name = 'like'
  AND deleted_at IS NULL
  AND target_id = ANY($2::varchar[])
`

type GetLikedTargetsParams struct {
	ActorID   int64
	TargetIds []string
}

// -------------------------------
// 3. Which of the given targets a persona currently likes
// -------------------------------
func (q *Queries) GetLikedTargets(ctx context.Context, arg GetLikedTargetsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLikedTargets, arg.ActorID, pq.Array(arg.TargetIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var target_id string
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetaFromEvents = `-- name: GetMetaFromEvents :many
SELECT
    name,
    target_id,
    COUNT(*) AS count
FROM events
WHERE name IN ('comment', 'like')
  AND target_id = $1
  AND deleted_at IS NULL
GROUP BY name, target_id
`

type GetMetaFromEventsRow struct {
	Name     EventEnum
	TargetID string
	Count    int64
}

// -------------------------------
// 2.1 Get events comments and likes per post
// -------------------------------
func (q *Queries) GetMetaFromEvents(ctx context.Context, targetID string) ([]GetMetaFromEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMetaFromEvents, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMetaFromEventsRow
	for rows.Next() {
		var i GetMetaFromEventsRow
		if err := rows.Scan(&i.Name, &i.TargetID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserLikedTarget = `-- name: IsUserLikedTarget :one
SELECT
    COUNT(*) > 0 AS liked
FROM events
WHERE name = 'like'
  AND target_id = $1
  AND actor_id = $2
  AND deleted_at IS NULL
`

type IsUserLikedTargetParams struct {
	TargetID string
	ActorID  int64
}

// ------------------------------
// 5. is user liked a target
// ------------------------------
func (q *Queries) IsUserLikedTarget(ctx context.Context, arg IsUserLikedTargetParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserLikedTarget, arg.TargetID, arg.ActorID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const softDeleteObjectEvents = `-- name: SoftDeleteObjectEvents :execrows
UPDATE events
SET deleted_at = NOW(), updated_at = NOW()
WHERE object_id = $1
  AND deleted_at IS NULL
`

// ------------------------------
// 7. Soft delete the events of a deleted post or comment
// ------------------------------
func (q *Queries) SoftDeleteObjectEvents(ctx context.Context, objectID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteObjectEvents, objectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unlikeEvent = `-- name: UnlikeEvent :exec
UPDATE events
SET deleted_at = NOW(), updated_at = NOW()
WHERE name = 'like'
  AND target_id = $1
  AND actor_id = $2
  AND deleted_at IS NULL
`

type UnlikeEventParams struct {
	TargetID string
	ActorID  int64
}

// ------------------------------
// 6. Unlike (soft delete) a like event
// ------------------------------
func (q *Queries) UnlikeEvent(ctx context.Context, arg UnlikeEventParams) error {
	_, err := q.db.ExecContext(ctx, unlikeEvent, arg.TargetID, arg.ActorID)
	return err
}
