// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geo.query.sql

package db

import (
	"context"
	"database/sql"
)

const listCitiesByState = `-- name: ListCitiesByState :many
SELECT 
    c.id,
    c.name
FROM public.cities c
JOIN public.states s ON s.id = c.state_id
WHERE c.state_id = $1
  AND c.name ILIKE '%' || COALESCE($2::text, '') || '%'
ORDER BY c.name ASC
`

type ListCitiesByStateParams struct {
	StateID sql.NullInt64
	Name    sql.NullString
}

type ListCitiesByStateRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListCitiesByState(ctx context.Context, arg ListCitiesByStateParams) ([]ListCitiesByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listCitiesByState, arg.StateID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCitiesByStateRow
	for rows.Next() {
		var i ListCitiesByStateRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT 
    id,
    name
FROM public.countries
WHERE name ILIKE '%' || COALESCE($1::text, '') || '%'
ORDER BY name ASC
`

type ListCountriesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListCountries(ctx context.Context, name sql.NullString) ([]ListCountriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCountries, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCountriesRow
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesByCountry = `-- name: ListStatesByCountry :many
SELECT 
    s.id,
    s.name
FROM public.states s
JOIN public.countries c ON c.id = s.country_id
WHERE s.country_id = $1
  AND s.name ILIKE '%' || COALESCE($2::text, '') || '%'
ORDER BY s.name ASC
`

type ListStatesByCountryParams struct {
	CountryID sql.NullInt64
	Name      sql.NullString
}

type ListStatesByCountryRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListStatesByCountry(ctx context.Context, arg ListStatesByCountryParams) ([]ListStatesByCountryRow, error) {
	rows, err := q.db.QueryContext(ctx, listStatesByCountry, arg.CountryID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatesByCountryRow
	for rows.Next() {
		var i ListStatesByCountryRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
