// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type EventActionEnum string

const (
	EventActionEnumCreate EventActionEnum = "create"
	EventActionEnumUpdate EventActionEnum = "update"
	EventActionEnumDelete EventActionEnum = "delete"
)

func (e *EventActionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventActionEnum(s)
	case string:
		*e = EventActionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EventActionEnum: %T", src)
	}
	return nil
}

type NullEventActionEnum struct {
	EventActionEnum EventActionEnum
	Valid           bool // Valid is true if EventActionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventActionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EventActionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventActionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventActionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventActionEnum), nil
}

type EventEnum string

const (
	EventEnumPost    EventEnum = "post"
	EventEnumComment EventEnum = "comment"
	EventEnumLike    EventEnum = "like"
)

func (e *EventEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventEnum(s)
	case string:
		*e = EventEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EventEnum: %T", src)
	}
	return nil
}

type NullEventEnum struct {
	EventEnum EventEnum
	Valid     bool // Valid is true if EventEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EventEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventEnum), nil
}

type EventTargetTypeEnum string

const (
	EventTargetTypeEnumUSER    EventTargetTypeEnum = "USER"
	EventTargetTypeEnumCHANNEL EventTargetTypeEnum = "CHANNEL"
	EventTargetTypeEnumPOST    EventTargetTypeEnum = "POST"
	EventTargetTypeEnumCOMMENT EventTargetTypeEnum = "COMMENT"
)

func (e *EventTargetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventTargetTypeEnum(s)
	case string:
		*e = EventTargetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EventTargetTypeEnum: %T", src)
	}
	return nil
}

type NullEventTargetTypeEnum struct {
	EventTargetTypeEnum EventTargetTypeEnum
	Valid               bool // Valid is true if EventTargetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventTargetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EventTargetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventTargetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventTargetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventTargetTypeEnum), nil
}

type OauthProvider string

const (
	OauthProviderGoogle   OauthProvider = "google"
	OauthProviderGithub   OauthProvider = "github"
	OauthProviderLinkedin OauthProvider = "linkedin"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider
	Valid         bool // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type OwnerEnum string

const (
	OwnerEnumUSER    OwnerEnum = "USER"
	OwnerEnumCHANNEL OwnerEnum = "CHANNEL"
)

func (e *OwnerEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OwnerEnum(s)
	case string:
		*e = OwnerEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OwnerEnum: %T", src)
	}
	return nil
}

type NullOwnerEnum struct {
	OwnerEnum OwnerEnum
	Valid     bool // Valid is true if OwnerEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOwnerEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OwnerEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OwnerEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOwnerEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OwnerEnum), nil
}

type Channel struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Banner      string
	OwnerID     int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type ChannelFollower struct {
	ID           int32
	ChannelID    int64
	UserID       int64
	FollowedAt   sql.NullTime
	UnfollowedAt sql.NullTime
}

type ChannelMember struct {
	ID        int32
	ChannelID int64
	UserID    int64
	JoinedAt  sql.NullTime
	LeftAt    sql.NullTime
}

type ChannelRole struct {
	ChannelID int64
	RoleID    int32
	UserID    int64
	DeletedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Event struct {
	ID         int64
	Name       EventEnum
	Action     EventActionEnum
	TargetID   string
	TargetType EventTargetTypeEnum
	Owner      OwnerEnum
	OwnerID    int64
	ActorID    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

type PostReference struct {
	ID        int32
	MongoID   string
	OwnerType string
	OwnerID   int64
	CreatedAt sql.NullTime
}

type Role struct {
	ID          int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type User struct {
	ID                     int64
	Uuid                   uuid.NullUUID
	FirstName              string
	LastName               string
	Phone                  string
	EmailAddress           string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              sql.NullTime
	HashedPassword         sql.NullString
	Thumbnail              sql.NullString
	IsVerified             sql.NullBool
	Bio                    sql.NullString
	PostalCode             sql.NullString
	OtherPlatformsAccounts []string
	CountryID              sql.NullInt64
	StateID                sql.NullInt64
	CityID                 sql.NullInt64
	OauthProvider          NullOauthProvider
}

type UserRole struct {
	UserID    int64
	RoleID    int32
	DeletedAt sql.NullTime
	UpdatedAt sql.NullTime
}
