// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ChannelMembershipStatusEnum string

const (
	ChannelMembershipStatusEnumPending  ChannelMembershipStatusEnum = "pending"
	ChannelMembershipStatusEnumActive   ChannelMembershipStatusEnum = "active"
	ChannelMembershipStatusEnumRejected ChannelMembershipStatusEnum = "rejected"
)

func (e *ChannelMembershipStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelMembershipStatusEnum(s)
	case string:
		*e = ChannelMembershipStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelMembershipStatusEnum: %T", src)
	}
	return nil
}

type NullChannelMembershipStatusEnum struct {
	ChannelMembershipStatusEnum ChannelMembershipStatusEnum
	Valid                       bool // Valid is true if ChannelMembershipStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelMembershipStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelMembershipStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelMembershipStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelMembershipStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelMembershipStatusEnum), nil
}

type ChannelVisibilityEnum string

const (
	ChannelVisibilityEnumPublic  ChannelVisibilityEnum = "public"
	ChannelVisibilityEnumPrivate ChannelVisibilityEnum = "private"
)

func (e *ChannelVisibilityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelVisibilityEnum(s)
	case string:
		*e = ChannelVisibilityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelVisibilityEnum: %T", src)
	}
	return nil
}

type NullChannelVisibilityEnum struct {
	ChannelVisibilityEnum ChannelVisibilityEnum
	Valid                 bool // Valid is true if ChannelVisibilityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelVisibilityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelVisibilityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelVisibilityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelVisibilityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelVisibilityEnum), nil
}

type EventActionEnum string

const (
	EventActionEnumCreate EventActionEnum = "create"
	EventActionEnumUpdate EventActionEnum = "update"
	EventActionEnumDelete EventActionEnum = "delete"
)

func (e *EventActionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventActionEnum(s)
	case string:
		*e = EventActionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EventActionEnum: %T", src)
	}
	return nil
}

type NullEventActionEnum struct {
	EventActionEnum EventActionEnum
	Valid           bool // Valid is true if EventActionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventActionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EventActionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventActionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventActionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventActionEnum), nil
}

type EventEnum string

const (
	EventEnumPost    EventEnum = "post"
	EventEnumComment EventEnum = "comment"
	EventEnumLike    EventEnum = "like"
)

func (e *EventEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventEnum(s)
	case string:
		*e = EventEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EventEnum: %T", src)
	}
	return nil
}

type NullEventEnum struct {
	EventEnum EventEnum
	Valid     bool // Valid is true if EventEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EventEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventEnum), nil
}

type EventTargetTypeEnum string

const (
	EventTargetTypeEnumPERSONA EventTargetTypeEnum = "PERSONA"
	EventTargetTypeEnumCHANNEL EventTargetTypeEnum = "CHANNEL"
	EventTargetTypeEnumPOST    EventTargetTypeEnum = "POST"
	EventTargetTypeEnumCOMMENT EventTargetTypeEnum = "COMMENT"
)

func (e *EventTargetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventTargetTypeEnum(s)
	case string:
		*e = EventTargetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EventTargetTypeEnum: %T", src)
	}
	return nil
}

type NullEventTargetTypeEnum struct {
	EventTargetTypeEnum EventTargetTypeEnum
	Valid               bool // Valid is true if EventTargetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventTargetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EventTargetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventTargetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventTargetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventTargetTypeEnum), nil
}

type NotificationKindEnum string

const (
	NotificationKindEnumPostComment        NotificationKindEnum = "post_comment"
	NotificationKindEnumCommentReply       NotificationKindEnum = "comment_reply"
	NotificationKindEnumPostLike           NotificationKindEnum = "post_like"
	NotificationKindEnumCommentLike        NotificationKindEnum = "comment_like"
	NotificationKindEnumJoinRequest        NotificationKindEnum = "join_request"
	NotificationKindEnumRequestApproved    NotificationKindEnum = "request_approved"
	NotificationKindEnumRemovedFromChannel NotificationKindEnum = "removed_from_channel"
)

func (e *NotificationKindEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationKindEnum(s)
	case string:
		*e = NotificationKindEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationKindEnum: %T", src)
	}
	return nil
}

type NullNotificationKindEnum struct {
	NotificationKindEnum NotificationKindEnum
	Valid                bool // Valid is true if NotificationKindEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationKindEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationKindEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationKindEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationKindEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationKindEnum), nil
}

type NotificationScopeEnum string

const (
	NotificationScopeEnumCHANNEL NotificationScopeEnum = "CHANNEL"
)

func (e *NotificationScopeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationScopeEnum(s)
	case string:
		*e = NotificationScopeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationScopeEnum: %T", src)
	}
	return nil
}

type NullNotificationScopeEnum struct {
	NotificationScopeEnum NotificationScopeEnum
	Valid                 bool // Valid is true if NotificationScopeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationScopeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationScopeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationScopeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationScopeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationScopeEnum), nil
}

type NotificationSubjectEnum string

const (
	NotificationSubjectEnumPOST    NotificationSubjectEnum = "POST"
	NotificationSubjectEnumCOMMENT NotificationSubjectEnum = "COMMENT"
	NotificationSubjectEnumCHANNEL NotificationSubjectEnum = "CHANNEL"
	NotificationSubjectEnumPERSONA NotificationSubjectEnum = "PERSONA"
)

func (e *NotificationSubjectEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationSubjectEnum(s)
	case string:
		*e = NotificationSubjectEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationSubjectEnum: %T", src)
	}
	return nil
}

type NullNotificationSubjectEnum struct {
	NotificationSubjectEnum NotificationSubjectEnum
	Valid                   bool // Valid is true if NotificationSubjectEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationSubjectEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationSubjectEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationSubjectEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationSubjectEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationSubjectEnum), nil
}

type OauthProvider string

const (
	OauthProviderGoogle   OauthProvider = "google"
	OauthProviderGithub   OauthProvider = "github"
	OauthProviderLinkedin OauthProvider = "linkedin"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider
	Valid         bool // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type OwnerEnum string

const (
	OwnerEnumPERSONA OwnerEnum = "PERSONA"
	OwnerEnumCHANNEL OwnerEnum = "CHANNEL"
)

func (e *OwnerEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OwnerEnum(s)
	case string:
		*e = OwnerEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OwnerEnum: %T", src)
	}
	return nil
}

type NullOwnerEnum struct {
	OwnerEnum OwnerEnum
	Valid     bool // Valid is true if OwnerEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOwnerEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OwnerEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OwnerEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOwnerEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OwnerEnum), nil
}

type PersonaPrivacyEnum string

const (
	PersonaPrivacyEnumPublic  PersonaPrivacyEnum = "public"
	PersonaPrivacyEnumPrivate PersonaPrivacyEnum = "private"
	PersonaPrivacyEnumOnlyMe  PersonaPrivacyEnum = "only_me"
)

func (e *PersonaPrivacyEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonaPrivacyEnum(s)
	case string:
		*e = PersonaPrivacyEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonaPrivacyEnum: %T", src)
	}
	return nil
}

type NullPersonaPrivacyEnum struct {
	PersonaPrivacyEnum PersonaPrivacyEnum
	Valid              bool // Valid is true if PersonaPrivacyEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonaPrivacyEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PersonaPrivacyEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonaPrivacyEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonaPrivacyEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonaPrivacyEnum), nil
}

type RelationshipEnum string

const (
	RelationshipEnumFollower RelationshipEnum = "follower"
	RelationshipEnumBlocked  RelationshipEnum = "blocked"
	RelationshipEnumMuted    RelationshipEnum = "muted"
)

func (e *RelationshipEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RelationshipEnum(s)
	case string:
		*e = RelationshipEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RelationshipEnum: %T", src)
	}
	return nil
}

type NullRelationshipEnum struct {
	RelationshipEnum RelationshipEnum
	Valid            bool // Valid is true if RelationshipEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationshipEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RelationshipEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelationshipEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationshipEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelationshipEnum), nil
}

type Channel struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Banner      string
	OwnerID     int64
	Visibility  ChannelVisibilityEnum
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type ChannelFollower struct {
	ID           int32
	ChannelID    int64
	PersonaID    int64
	FollowedAt   sql.NullTime
	UnfollowedAt sql.NullTime
}

type ChannelMember struct {
	ID        int32
	ChannelID int64
	PersonaID int64
	JoinedAt  sql.NullTime
	LeftAt    sql.NullTime
	Status    ChannelMembershipStatusEnum
}

type ChannelRole struct {
	ChannelID int64
	RoleID    int32
	PersonaID int64
	DeletedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type City struct {
	ID          int64
	Name        string
	StateID     int64
	StateCode   string
	CountryID   int64
	CountryCode string
	Latitude    string
	Longitude   string
	Timezone    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Flag        int16
	WikiDataId  sql.NullString
}

type Country struct {
	ID             int64
	Name           string
	Iso3           sql.NullString
	NumericCode    sql.NullString
	Iso2           sql.NullString
	Phonecode      sql.NullString
	Capital        sql.NullString
	Currency       sql.NullString
	CurrencyName   sql.NullString
	CurrencySymbol sql.NullString
	Tld            sql.NullString
	Native         sql.NullString
	Region         sql.NullString
	RegionID       sql.NullInt64
	Subregion      sql.NullString
	SubregionID    sql.NullInt64
	Nationality    sql.NullString
	Timezones      sql.NullString
	Translations   sql.NullString
	Latitude       sql.NullString
	Longitude      sql.NullString
	Emoji          sql.NullString
	EmojiU         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      time.Time
	Flag           int16
	WikiDataId     sql.NullString
}

type Event struct {
	ID         int64
	Name       EventEnum
	Action     EventActionEnum
	TargetID   string
	TargetType EventTargetTypeEnum
	Owner      OwnerEnum
	OwnerID    int64
	ActorID    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	ObjectID   string
}

type Interest struct {
	ID        int64
	Name      string
	PicUrl    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Notification struct {
	ID          int64
	RecipientID int64
	Kind        NotificationKindEnum
	GroupKey    string
	SubjectType NotificationSubjectEnum
	SubjectID   string
	ScopeType   NullNotificationScopeEnum
	ScopeID     sql.NullInt64
	ActorID     sql.NullInt64
	Data        pqtype.NullRawMessage
	LastEventAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ReadAt      sql.NullTime
	DeletedAt   sql.NullTime
}

type Persona struct {
	ID          int64
	UserID      int64
	Name        string
	Description string
	Slug        string
	FirstName   string
	LastName    string
	Thumbnail   sql.NullString
	Bio         sql.NullString
	Privacy     PersonaPrivacyEnum
	IsDefault   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type PersonaFollower struct {
	PersonaID         int64
	FollowerPersonaID int64
	FollowedAt        sql.NullTime
	UnfollowedAt      sql.NullTime
}

type PersonaFriendGroup struct {
	ID             int64
	OwnerPersonaID sql.NullInt64
	Name           string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type PersonaFriendGroupMember struct {
	GroupID         int64
	MemberPersonaID int64
}

type PersonaInterest struct {
	PersonaID  int64
	InterestID int64
}

type PersonaRelationship struct {
	SourcePersonaID int64
	TargetPersonaID int64
	Relationship    RelationshipEnum
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type PostReference struct {
	ID        int32
	MongoID   string
	OwnerType string
	OwnerID   int64
	CreatedAt sql.NullTime
}

type Region struct {
	ID           int64
	Name         string
	Translations sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    time.Time
	Flag         int16
	WikiDataId   sql.NullString
}

type Role struct {
	ID          int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type State struct {
	ID          int64
	Name        string
	CountryID   int64
	CountryCode string
	FipsCode    sql.NullString
	Iso2        sql.NullString
	Iso31662    sql.NullString
	Type        sql.NullString
	Level       sql.NullInt32
	ParentID    sql.NullInt64
	Native      sql.NullString
	Latitude    sql.NullString
	Longitude   sql.NullString
	Timezone    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   time.Time
	Flag        int16
	WikiDataId  sql.NullString
}

type Subregion struct {
	ID           int64
	Name         string
	Translations sql.NullString
	RegionID     int64
	CreatedAt    sql.NullTime
	UpdatedAt    time.Time
	Flag         int16
	WikiDataId   sql.NullString
}

type User struct {
	ID                     int64
	Uuid                   uuid.NullUUID
	FirstName              string
	LastName               string
	EmailAddress           string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              sql.NullTime
	HashedPassword         sql.NullString
	Thumbnail              sql.NullString
	IsVerified             sql.NullBool
	PostalCode             sql.NullString
	OtherPlatformsAccounts []string
	CountryID              sql.NullInt64
	StateID                sql.NullInt64
	CityID                 sql.NullInt64
	OauthProvider          NullOauthProvider
	OnboardingCompleted    sql.NullBool
	OnboardingStep         sql.NullInt32
}

type UserRole struct {
	UserID    int64
	RoleID    int32
	DeletedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserVerification struct {
	ID               int64
	UserID           sql.NullInt64
	VerificationCode string
	ExpiresAt        sql.NullTime
	CreatedAt        time.Time
	FailedAttempts   int32
	MaxAttempts      int32
	LastSentAt       sql.NullTime
	VerifiedAt       sql.NullTime
	IsExpired        sql.NullBool
}
