// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)
FROM notifications n
JOIN channels c ON c.id = n.channel_id AND c.deleted_at IS NULL
WHERE n.recipient_id = $1::bigint
  AND n.deleted_at IS NULL
  AND n.read_at IS NULL
  AND (
      n.kind IN ('join_request', 'request_approved', 'removed_from_channel')
      OR c.visibility = 'public'
      OR EXISTS (
          SELECT 1
          FROM channel_members cm
          WHERE cm.channel_id = n.channel_id
            AND cm.persona_id = n.recipient_id
            AND cm.left_at IS NULL AND cm.status = 'active'
      )
  )
`

// -------------------------------
// 5. Unread badge
// -------------------------------
// Same visibility filter as ListNotifications.
func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChannelModeratorIDs = `-- name: ListChannelModeratorIDs :many
SELECT c.owner_id AS persona_id
FROM channels c
WHERE c.id = $1::bigint
  AND c.deleted_at IS NULL
UNION
SELECT cr.persona_id
FROM channel_roles cr
JOIN roles r ON r.id = cr.role_id
JOIN channels c ON c.id = cr.channel_id AND c.deleted_at IS NULL
WHERE cr.channel_id = $1::bigint
  AND cr.deleted_at IS NULL
  AND r.name IN ('moderator', 'Administrator')
`

// -------------------------------
// 8. Who handles a channel's join requests
// -------------------------------
// The owner and channel moderators/Administrators. Global Administrators are
// left out, or they would be notified about every channel.
func (q *Queries) ListChannelModeratorIDs(ctx context.Context, channelID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChannelModeratorIDs, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var persona_id int64
		if err := rows.Scan(&persona_id); err != nil {
			return nil, err
		}
		items = append(items, persona_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRecipientsByGroup = `-- name: ListNotificationRecipientsByGroup :many
SELECT recipient_id
FROM notifications
WHERE group_key = $1::varchar
  AND deleted_at IS NULL
`

// -------------------------------
// 2.1 Who has an active notification for a group
// -------------------------------
// Removal events (unlike, deleted comment, resolved join request) do not
// name the recipient; the notifier recounts for the recipients found here.
func (q *Queries) ListNotificationRecipientsByGroup(ctx context.Context, groupKey string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationRecipientsByGroup, groupKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var recipient_id int64
		if err := rows.Scan(&recipient_id); err != nil {
			return nil, err
		}
		items = append(items, recipient_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.recipient_id, n.kind, n.group_key, n.object_id, n.channel_id, n.actor_id, n.last_event_at, n.created_at, n.updated_at, n.read_at, n.deleted_at
FROM notifications n
JOIN channels c ON c.id = n.channel_id AND c.deleted_at IS NULL
WHERE n.recipient_id = $1::bigint
  AND n.deleted_at IS NULL
  AND (
      $2::timestamptz IS NULL
      OR (n.updated_at, n.id) < ($2::timestamptz, $3::bigint)
  )
  AND (
      n.kind IN ('join_request', 'request_approved', 'removed_from_channel')
      OR c.visibility = 'public'
      OR EXISTS (
          SELECT 1
          FROM channel_members cm
          WHERE cm.channel_id = n.channel_id
            AND cm.persona_id = n.recipient_id
            AND cm.left_at IS NULL AND cm.status = 'active'
      )
  )
ORDER BY n.updated_at DESC, n.id DESC
LIMIT $4::int
`

type ListNotificationsParams struct {
	RecipientID     int64
	CursorUpdatedAt sql.NullTime
	CursorID        sql.NullInt64
	PageSize        int32
}

// -------------------------------
// 4. A persona's notifications, newest first
// -------------------------------
// Keyset paged: pass the last row's (updated_at, id) as the cursor, or NULLs
// for the first page. Content notifications of a private channel are hidden
// while the persona is not an active member (same rule as access.CanRead);
// membership kinds always show.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications,
		arg.RecipientID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.GroupKey,
			&i.ObjectID,
			&i.ChannelID,
			&i.ActorID,
			&i.LastEventAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = NOW()
WHERE recipient_id = $1::bigint
  AND deleted_at IS NULL
  AND read_at IS NULL
`

// -------------------------------
// 7. Mark all of a persona's notifications read
// -------------------------------
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsRead, recipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
UPDATE notifications
SET read_at = NOW()
WHERE recipient_id = $1::bigint
  AND id = ANY($2::bigint[])
  AND read_at IS NULL
`

type MarkNotificationsReadParams struct {
	RecipientID int64
	Ids         []int64
}

// -------------------------------
// 6. Mark some of a persona's notifications read
// -------------------------------
func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationsRead, arg.RecipientID, pq.Array(arg.Ids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recountCommenters = `-- name: RecountCommenters :many

SELECT
    target_id,
    COUNT(DISTINCT actor_id)::bigint AS count,
    (ARRAY_AGG(actor_id ORDER BY created_at DESC, id DESC))[1]::bigint AS latest_actor_id
FROM events
WHERE name = 'comment'
  AND target_id = ANY($1::varchar[])
  AND actor_id <> $2::bigint
  AND deleted_at IS NULL
GROUP BY target_id
`

type RecountCommentersParams struct {
	TargetIds   []string
	RecipientID int64
}

type RecountCommentersRow struct {
	TargetID      string
	Count         int64
	LatestActorID int64
}

// -------------------------------
// 9. Recounts for aggregated kinds
// -------------------------------
// Each returns, per group, how many other personas acted and the latest of
// them. The recipient's own activity is excluded. A group missing from the
// result has a count of zero.
// Commenters on posts or comments (post_comment, comment_reply).
func (q *Queries) RecountCommenters(ctx context.Context, arg RecountCommentersParams) ([]RecountCommentersRow, error) {
	rows, err := q.db.QueryContext(ctx, recountCommenters, pq.Array(arg.TargetIds), arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecountCommentersRow
	for rows.Next() {
		var i RecountCommentersRow
		if err := rows.Scan(&i.TargetID, &i.Count, &i.LatestActorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recountLikers = `-- name: RecountLikers :many
SELECT
    object_id,
    COUNT(DISTINCT actor_id)::bigint AS count,
    (ARRAY_AGG(actor_id ORDER BY created_at DESC, id DESC))[1]::bigint AS latest_actor_id
FROM events
WHERE name = 'like'
  AND object_id = ANY($1::varchar[])
  AND actor_id <> $2::bigint
  AND deleted_at IS NULL
GROUP BY object_id
`

type RecountLikersParams struct {
	ObjectIds   []string
	RecipientID int64
}

type RecountLikersRow struct {
	ObjectID      string
	Count         int64
	LatestActorID int64
}

// Likers of posts or comments (post_like, comment_like).
func (q *Queries) RecountLikers(ctx context.Context, arg RecountLikersParams) ([]RecountLikersRow, error) {
	rows, err := q.db.QueryContext(ctx, recountLikers, pq.Array(arg.ObjectIds), arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecountLikersRow
	for rows.Next() {
		var i RecountLikersRow
		if err := rows.Scan(&i.ObjectID, &i.Count, &i.LatestActorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recountPendingJoinRequests = `-- name: RecountPendingJoinRequests :many
SELECT
    channel_id,
    COUNT(*)::bigint AS count,
    (ARRAY_AGG(persona_id ORDER BY joined_at DESC, id DESC))[1]::bigint AS latest_actor_id
FROM channel_members
WHERE channel_id = ANY($1::bigint[])
  AND persona_id <> $2::bigint
  AND left_at IS NULL
  AND status = 'pending'
GROUP BY channel_id
`

type RecountPendingJoinRequestsParams struct {
	ChannelIds  []int64
	RecipientID int64
}

type RecountPendingJoinRequestsRow struct {
	ChannelID     int64
	Count         int64
	LatestActorID int64
}

// Pending join requests on channels (join_request).
func (q *Queries) RecountPendingJoinRequests(ctx context.Context, arg RecountPendingJoinRequestsParams) ([]RecountPendingJoinRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, recountPendingJoinRequests, pq.Array(arg.ChannelIds), arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecountPendingJoinRequestsRow
	for rows.Next() {
		var i RecountPendingJoinRequestsRow
		if err := rows.Scan(&i.ChannelID, &i.Count, &i.LatestActorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotificationsByGroup = `-- name: SoftDeleteNotificationsByGroup :many
UPDATE notifications
SET deleted_at = NOW(),
    last_event_at = GREATEST(last_event_at, $1::timestamptz)
WHERE group_key = $2::varchar
  AND deleted_at IS NULL
RETURNING id, recipient_id
`

type SoftDeleteNotificationsByGroupParams struct {
	EventAt  time.Time
	GroupKey string
}

type SoftDeleteNotificationsByGroupRow struct {
	ID          int64
	RecipientID int64
}

// -------------------------------
// 2. Remove a group whose recount reached zero
// -------------------------------
// last_event_at moves forward so a redelivered older create cannot revive it.
func (q *Queries) SoftDeleteNotificationsByGroup(ctx context.Context, arg SoftDeleteNotificationsByGroupParams) ([]SoftDeleteNotificationsByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, softDeleteNotificationsByGroup, arg.EventAt, arg.GroupKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoftDeleteNotificationsByGroupRow
	for rows.Next() {
		var i SoftDeleteNotificationsByGroupRow
		if err := rows.Scan(&i.ID, &i.RecipientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotificationsByObject = `-- name: SoftDeleteNotificationsByObject :many
UPDATE notifications
SET deleted_at = NOW(),
    last_event_at = GREATEST(last_event_at, $1::timestamptz)
WHERE object_id = $2::varchar
  AND deleted_at IS NULL
RETURNING id, recipient_id
`

type SoftDeleteNotificationsByObjectParams struct {
	EventAt  time.Time
	ObjectID string
}

type SoftDeleteNotificationsByObjectRow struct {
	ID          int64
	RecipientID int64
}

// -------------------------------
// 3. Remove everything about a deleted post or comment
// -------------------------------
func (q *Queries) SoftDeleteNotificationsByObject(ctx context.Context, arg SoftDeleteNotificationsByObjectParams) ([]SoftDeleteNotificationsByObjectRow, error) {
	rows, err := q.db.QueryContext(ctx, softDeleteNotificationsByObject, arg.EventAt, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoftDeleteNotificationsByObjectRow
	for rows.Next() {
		var i SoftDeleteNotificationsByObjectRow
		if err := rows.Scan(&i.ID, &i.RecipientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotification = `-- name: UpsertNotification :one
INSERT INTO notifications (
    recipient_id,
    kind,
    group_key,
    object_id,
    channel_id,
    actor_id,
    last_event_at,
    updated_at
)
VALUES (
    $1::bigint,
    $2::notification_kind_enum,
    $3::varchar,
    $4::varchar,
    $5::bigint,
    $6::bigint,
    $7::timestamptz,
    $7::timestamptz
)
ON CONFLICT (recipient_id, group_key) DO UPDATE
SET actor_id = EXCLUDED.actor_id,
    last_event_at = EXCLUDED.last_event_at,
    updated_at = EXCLUDED.updated_at,
    read_at = NULL,
    deleted_at = NULL
WHERE notifications.last_event_at < EXCLUDED.last_event_at
RETURNING id
`

type UpsertNotificationParams struct {
	RecipientID int64
	Kind        NotificationKindEnum
	GroupKey    string
	ObjectID    sql.NullString
	ChannelID   int64
	ActorID     sql.NullInt64
	EventAt     time.Time
}

// -------------------------------
// 1. Create or revive a notification for new activity
// -------------------------------
// Moves the row to the top and marks it unread. An event no newer than the
// last one applied changes nothing and returns no row (sql.ErrNoRows), so
// the caller publishes only real changes.
func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertNotification,
		arg.RecipientID,
		arg.Kind,
		arg.GroupKey,
		arg.ObjectID,
		arg.ChannelID,
		arg.ActorID,
		arg.EventAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
