// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persona.sql

package db

import (
	"context"
)

const getDefaultPersonaByUserId = `-- name: GetDefaultPersonaByUserId :one
SELECT id, user_id, slug, first_name, last_name, thumbnail, bio, privacy, is_default, created_at, updated_at, deleted_at
FROM personas
WHERE user_id = $1 AND is_default = TRUE
LIMIT 1
`

// ------------------------------
// 1.GetDefaultPersonaByUserId
// ------------------------------
func (q *Queries) GetDefaultPersonaByUserId(ctx context.Context, userID int64) (Persona, error) {
	row := q.db.QueryRowContext(ctx, getDefaultPersonaByUserId, userID)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.FirstName,
		&i.LastName,
		&i.Thumbnail,
		&i.Bio,
		&i.Privacy,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
