// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persona.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createPersona = `-- name: CreatePersona :one
INSERT INTO personas (user_id, name, description, first_name, last_name, thumbnail, Bio, slug, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, FALSE, NOW(), NOW())
RETURNING id, user_id, name, description, slug, first_name, last_name, thumbnail, bio, privacy, is_default, created_at, updated_at, deleted_at
`

type CreatePersonaParams struct {
	UserID      int64
	Name        string
	Description string
	FirstName   string
	LastName    string
	Thumbnail   sql.NullString
	Bio         sql.NullString
	Slug        string
}

// ------------------------------
// 3. CreatePersona
// ------------------------------
func (q *Queries) CreatePersona(ctx context.Context, arg CreatePersonaParams) (Persona, error) {
	row := q.db.QueryRowContext(ctx, createPersona,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.FirstName,
		arg.LastName,
		arg.Thumbnail,
		arg.Bio,
		arg.Slug,
	)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.FirstName,
		&i.LastName,
		&i.Thumbnail,
		&i.Bio,
		&i.Privacy,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDefaultPersonaByUserId = `-- name: GetDefaultPersonaByUserId :one
SELECT id, user_id, name, description, slug, first_name, last_name, thumbnail, bio, privacy, is_default, created_at, updated_at, deleted_at
FROM personas
WHERE user_id = $1 AND is_default = TRUE
LIMIT 1
`

// ------------------------------
// 1.GetDefaultPersonaByUserId
// ------------------------------
func (q *Queries) GetDefaultPersonaByUserId(ctx context.Context, userID int64) (Persona, error) {
	row := q.db.QueryRowContext(ctx, getDefaultPersonaByUserId, userID)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.FirstName,
		&i.LastName,
		&i.Thumbnail,
		&i.Bio,
		&i.Privacy,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPersonaBasicInfo = `-- name: GetPersonaBasicInfo :one
SELECT u.id, u.name, u.slug, u.first_name, u.last_name, u.thumbnail, u.created_at, u.updated_at, u.privacy,
      (SELECT COALESCE(json_agg(json_build_object(
               'id', c.id,
               'name', c.name,
               'description', c.description,
               'created_at', c.created_at
           )), '[]'::json)
           FROM channel_members cm
           JOIN channels c ON c.id = cm.channel_id
           WHERE cm.persona_id = u.id AND cm.left_at IS NULL
       ) AS joined_channels,
        (SELECT COALESCE(json_agg(json_build_object(
               'id', c.id,
               'name', c.name,
               'description', c.description,
               'created_at', c.created_at
           )), '[]'::json)
           FROM channel_followers cm
           JOIN channels c ON c.id = cm.channel_id
           WHERE cm.persona_id = u.id AND cm.unfollowed_at IS NULL
       ) AS followed_channels
FROM personas u
WHERE u.id = $1
  AND u.deleted_at IS NULL
`

type GetPersonaBasicInfoRow struct {
	ID               int64
	Name             string
	Slug             string
	FirstName        string
	LastName         string
	Thumbnail        sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	Privacy          PersonaPrivacyEnum
	JoinedChannels   pqtype.NullRawMessage
	FollowedChannels pqtype.NullRawMessage
}

// -------------------------------
// 7. Get Persona Basic Info
// -------------------------------
func (q *Queries) GetPersonaBasicInfo(ctx context.Context, id int64) (GetPersonaBasicInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonaBasicInfo, id)
	var i GetPersonaBasicInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FirstName,
		&i.LastName,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Privacy,
		&i.JoinedChannels,
		&i.FollowedChannels,
	)
	return i, err
}

const getPersonaByIdAndUserId = `-- name: GetPersonaByIdAndUserId :one
SELECT id, user_id, name, description, slug, first_name, last_name, thumbnail, bio, privacy, is_default, created_at, updated_at, deleted_at
FROM personas
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetPersonaByIdAndUserIdParams struct {
	ID     int64
	UserID int64
}

// ------------------------------
// 4. GetPersonaByIdAndUserId
// ------------------------------
func (q *Queries) GetPersonaByIdAndUserId(ctx context.Context, arg GetPersonaByIdAndUserIdParams) (Persona, error) {
	row := q.db.QueryRowContext(ctx, getPersonaByIdAndUserId, arg.ID, arg.UserID)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.FirstName,
		&i.LastName,
		&i.Thumbnail,
		&i.Bio,
		&i.Privacy,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPersonaFollowedChannels = `-- name: GetPersonaFollowedChannels :many
SELECT c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.created_at, c.updated_at, c.deleted_at
FROM channel_followers cf
JOIN channels c ON cf.channel_id = c.id
WHERE cf.persona_id = $1
  AND cf.unfollowed_at IS NULL
`

// -------------------------------
// 10. Get channels a persona follows
// -------------------------------
func (q *Queries) GetPersonaFollowedChannels(ctx context.Context, personaID int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getPersonaFollowedChannels, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonaJoinedChannels = `-- name: GetPersonaJoinedChannels :many
SELECT c.id, c.name, c.description, c.thumbnail, c.banner, c.owner_id, c.created_at, c.updated_at, c.deleted_at
FROM channel_members cm
JOIN channels c ON cm.channel_id = c.id
WHERE cm.persona_id = $1
  AND cm.left_at IS NULL
`

// -------------------------------
// 9. Get channels a persona has joined
// -------------------------------
func (q *Queries) GetPersonaJoinedChannels(ctx context.Context, personaID int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getPersonaJoinedChannels, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Banner,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonaStats = `-- name: GetPersonaStats :one
SELECT u.id,
       (SELECT COUNT(*) FROM channel_members cm WHERE cm.persona_id = u.id AND cm.left_at IS NULL) AS channels_joined,
       (SELECT COUNT(*) FROM channel_followers cf WHERE cf.persona_id = u.id AND cf.unfollowed_at IS NULL) AS channels_followed,
       (SELECT COUNT(*) FROM post_references pr WHERE pr.owner_type = 'PERSONA' AND pr.owner_id = u.id) AS posts_count
FROM personas u
WHERE u.id = $1
  AND u.deleted_at IS NULL
`

type GetPersonaStatsRow struct {
	ID               int64
	ChannelsJoined   int64
	ChannelsFollowed int64
	PostsCount       int64
}

// -------------------------------
// 8. Get persona stats
// -------------------------------
func (q *Queries) GetPersonaStats(ctx context.Context, id int64) (GetPersonaStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonaStats, id)
	var i GetPersonaStatsRow
	err := row.Scan(
		&i.ID,
		&i.ChannelsJoined,
		&i.ChannelsFollowed,
		&i.PostsCount,
	)
	return i, err
}

const getUserPersonasByUserId = `-- name: GetUserPersonasByUserId :many
SELECT id, user_id, name, description, slug, first_name, last_name, thumbnail, bio, privacy, is_default, created_at, updated_at, deleted_at
FROM personas
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

// ------------------------------
// 2. GetUserPersonasByUserId
// ------------------------------
func (q *Queries) GetUserPersonasByUserId(ctx context.Context, userID int64) ([]Persona, error) {
	rows, err := q.db.QueryContext(ctx, getUserPersonasByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Persona
	for rows.Next() {
		var i Persona
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.FirstName,
			&i.LastName,
			&i.Thumbnail,
			&i.Bio,
			&i.Privacy,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePersonaByID = `-- name: ResolvePersonaByID :one
SELECT id, first_name, last_name, thumbnail 
FROM personas 
WHERE id = $1 
AND deleted_at IS NULL LIMIT 1
`

type ResolvePersonaByIDRow struct {
	ID        int64
	FirstName string
	LastName  string
	Thumbnail sql.NullString
}

// -------------------------------
// 12. Resolve Persona By ID
// -------------------------------
func (q *Queries) ResolvePersonaByID(ctx context.Context, id int64) (ResolvePersonaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, resolvePersonaByID, id)
	var i ResolvePersonaByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Thumbnail,
	)
	return i, err
}
