// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.query.sql

package db

import (
	"context"
	"database/sql"
)

const assignUserRole = `-- name: AssignUserRole :one
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
RETURNING user_id, role_id, deleted_at, updated_at
`

type AssignUserRoleParams struct {
	UserID int64
	RoleID int32
}

// -------------------------------
// 7. Assign global role to a user
// -------------------------------
func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, assignUserRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignUserRoleInChannel = `-- name: AssignUserRoleInChannel :one
INSERT INTO channel_roles (channel_id, user_id, role_id)
VALUES ($1, $2, $3)
RETURNING channel_id, role_id, user_id, deleted_at, updated_at
`

type AssignUserRoleInChannelParams struct {
	ChannelID int64
	UserID    int64
	RoleID    int32
}

// -------------------------------
// 9. Assign role to user in a channel
// -------------------------------
func (q *Queries) AssignUserRoleInChannel(ctx context.Context, arg AssignUserRoleInChannelParams) (ChannelRole, error) {
	row := q.db.QueryRowContext(ctx, assignUserRoleInChannel, arg.ChannelID, arg.UserID, arg.RoleID)
	var i ChannelRole
	err := row.Scan(
		&i.ChannelID,
		&i.RoleID,
		&i.UserID,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	Name        string
	Description sql.NullString
}

// -------------------------------
// 1. Create a role
// -------------------------------
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

// -------------------------------
// 5. Delete role
// -------------------------------
func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getChannelRolesForUser = `-- name: GetChannelRolesForUser :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at, r.deleted_at
FROM channel_roles cr
JOIN roles r ON cr.role_id = r.id
JOIN channel_members cm ON cm.channel_id = cr.channel_id AND cm.user_id = $2
WHERE cr.channel_id = $1
  AND cr.deleted_at IS NULL
`

type GetChannelRolesForUserParams struct {
	ChannelID int64
	UserID    int64
}

// -------------------------------
// 11. Get user's role in a channel
// -------------------------------
func (q *Queries) GetChannelRolesForUser(ctx context.Context, arg GetChannelRolesForUserParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getChannelRolesForUser, arg.ChannelID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at, updated_at, deleted_at FROM roles WHERE name = $1
`

// -------------------------------
// 2. Get role by name
// -------------------------------
func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at, r.deleted_at
FROM user_roles ur
JOIN roles r ON ur.role_id = r.id
WHERE ur.user_id = $1
  AND ur.deleted_at IS NULL
  AND r.deleted_at IS NULL
`

// -------------------------------
// 6. Get all global roles for a user
// -------------------------------
func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at, updated_at, deleted_at FROM roles ORDER BY name
`

// -------------------------------
// 3. List all roles
// -------------------------------
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserRole = `-- name: RemoveUserRole :one
UPDATE user_roles
SET deleted_at = NOW()
WHERE user_id = $1 AND role_id = $2
RETURNING user_id, role_id, deleted_at, updated_at
`

type RemoveUserRoleParams struct {
	UserID int64
	RoleID int32
}

// -------------------------------
// 8. Remove global role from user (soft delete)
// -------------------------------
func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, removeUserRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeUserRoleInChannel = `-- name: RemoveUserRoleInChannel :one
UPDATE channel_roles
SET deleted_at = NOW()
WHERE channel_id = $1 AND user_id = $2 AND role_id = $3
RETURNING channel_id, role_id, user_id, deleted_at, updated_at
`

type RemoveUserRoleInChannelParams struct {
	ChannelID int64
	UserID    int64
	RoleID    int32
}

// -------------------------------
// 10. Remove role from user in a channel (soft delete)
// -------------------------------
func (q *Queries) RemoveUserRoleInChannel(ctx context.Context, arg RemoveUserRoleInChannelParams) (ChannelRole, error) {
	row := q.db.QueryRowContext(ctx, removeUserRoleInChannel, arg.ChannelID, arg.UserID, arg.RoleID)
	var i ChannelRole
	err := row.Scan(
		&i.ChannelID,
		&i.RoleID,
		&i.UserID,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = $1, description = $2 WHERE id = $3 RETURNING id, name, description, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	Name        string
	Description sql.NullString
	ID          int32
}

// -------------------------------
// 4. Update role
// -------------------------------
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
