package models

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"shared/external/db/nats"
	"shared/pkg/access"
	"shared/pkg/db"
	"shared/pkg/graph"
	"shared/pkg/graph/models"
	"shared/pkg/subject"
	portabletext "shared/util/portableText"
	"sync"
	"time"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input models.PostInput) (*models.PostGenericDocument, error) {
	// Create Object in Mongodb
	Collection := r.Objects
	personaId, err := getPersonaIdFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated: %w", err)
	}
	if err := r.authorizeOwner(ctx, &models.Owner{ID: input.Owner.ID, Type: input.Owner.Type}, personaId, true); err != nil {
		return nil, err
	}
	rawContent, err := json.Marshal(input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal content: %w", err)
	}

	object := &models.PostGenericDocument{
		ID:       newObjectID(),
		Type:     models.PostTypePost,
		ParentID: nil,
		AuthorID: personaId,
		Tags:     input.Tags,
		Owner: &models.Owner{
			ID:   input.Owner.ID,
			Type: input.Owner.Type,
		},
		Content:           portabletext.ParseContent(*input.Content),
		RawContent:        string(rawContent),
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
		Privacy:           models.Privacy(input.Privacy.String()),
		AllowedPersonaIds: input.AllowedPersonaIds,
		DeniedPersonaIds:  input.DeniedPersonaIds,
	}

	_, insertError := Collection.InsertOne(ctx, object)
	if insertError != nil {
		return nil, fmt.Errorf("failed to insert object: %w", insertError)
	}
	metaData := map[string]any{
		"object_id":  object.ID,
		"owner_id":   input.Owner.ID,
		"owner_type": input.Owner.Type,
		"author_id":  personaId,
		"tags":       input.Tags,
		"created_at": object.CreatedAt,
	}

	var ownerType db.OwnerEnum
	switch input.Owner.Type {
	case models.OwnerTypePersona:
		ownerType = db.OwnerEnumPERSONA
	case models.OwnerTypeChannel:
		ownerType = db.OwnerEnumCHANNEL
	default:
		ownerType = db.OwnerEnumPERSONA
	}

	event := db.CreateEventParams{
		Name:       db.EventEnumPost,
		Action:     db.EventActionEnumCreate,
		TargetID:   fmt.Sprintf("%d", input.Owner.ID),
		TargetType: db.EventTargetTypeEnumCHANNEL,
		Owner:      ownerType,
		OwnerID:    int64(input.Owner.ID),
		ActorID:    int64(personaId),
		ObjectID:   object.ID,
	}

	_, err = r.Queries.CreateEvent(ctx, event)

	if err != nil {
		log.Println("Warning: failed to create event:", err)
	}

	if err != nil {
		log.Println("Warning: failed to marshal metadata for NATS:", err)
	}
	var streamName = nats.CONTENT_EVENTS_STREAM
	subjectHelper := subject.New(&streamName, &models.Owner{
		ID:   input.Owner.ID,
		Type: input.Owner.Type,
	}, string(db.EventEnumPost), string(db.EventActionEnumCreate))

	err = r.NATS.PublishMessage(
		ctx,
		subjectHelper.GetSubject(),
		&nats.MessageType{Event: *models.EventMapper(event), Payload: metaData},
	)

	if err != nil {
		log.Println("Warning: failed to publish post creation event to NATS:", err)
	}

	return object, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input models.CommentInput) (*models.PostGenericDocument, error) {
	Collection := r.Objects
	personaId, err := getPersonaIdFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated: %w", err)
	}
	// Authorize and route against the parent's stored channel, never the
	// client's owner input.
	parent, err := r.loadObject(ctx, input.ParentID)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeOwner(ctx, parent.Owner, personaId, true); err != nil {
		return nil, err
	}
	owner := parent.Owner
	rawContent, err := json.Marshal(input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal content: %w", err)
	}

	object := &models.PostGenericDocument{
		ID:                newObjectID(),
		Type:              models.PostTypeComment,
		ParentID:          &input.ParentID,
		AuthorID:          personaId,
		Tags:              input.Tags,
		RawContent:        string(rawContent),
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
		Owner:             owner,
		Privacy:           models.Privacy(input.Privacy.String()),
		AllowedPersonaIds: input.AllowedPersonaIds,
		DeniedPersonaIds:  input.DeniedPersonaIds,
	}

	_, insertError := Collection.InsertOne(ctx, object)
	if insertError != nil {
		return nil, fmt.Errorf("failed to insert object: %w", insertError)
	}

	author, err := r.resolvePersonaCached(ctx, personaId)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve author: %w", err)
	}

	comment := models.Comment{
		ID:         object.ID,
		Type:       object.Type,
		ParentID:   *object.ParentID,
		AuthorID:   object.AuthorID,
		Author:     author,
		Tags:       object.Tags,
		RawContent: object.RawContent,
		CreatedAt:  object.CreatedAt,
		UpdatedAt:  object.UpdatedAt,
		Privacy:    object.Privacy,
		Edited:     object.Edited,
		Meta: &models.Meta{
			LikesCount:  0,
			SharesCount: 0,
			ViewsCount:  0,
		},
		PersonalizedMeta: &models.PersonalizedMeta{
			LikedByPersona:  false,
			SharedByPersona: false,
			ViewedByPersona: false,
			ACL: &models.ACL{
				CanView:    true,
				CanComment: true,
				CanReply:   true,
				CanLike:    true,
				CanShare:   true,
			},
		},
	}

	targetType := eventTargetType(parent.Type)

	event := db.CreateEventParams{
		Name:       db.EventEnumComment,
		Action:     db.EventActionEnumCreate,
		TargetID:   input.ParentID,
		TargetType: targetType,
		Owner:      db.OwnerEnum(owner.Type.String()),
		OwnerID:    owner.ID,
		ActorID:    int64(personaId),
		ObjectID:   object.ID,
	}

	_, err = r.Queries.CreateEvent(ctx, event)

	if err != nil {
		log.Println("Warning: failed to create event:", err)
	}

	if err != nil {
		log.Println("Warning: failed to marshal metadata for NATS:", err)
	}
	var streamName = nats.CONTENT_EVENTS_STREAM
	subjectHelper := subject.New(&streamName, owner, string(db.EventEnumComment), string(db.EventActionEnumCreate))

	err = r.NATS.PublishMessage(
		ctx,
		subjectHelper.GetSubject(),
		&nats.MessageType{Event: *models.EventMapper(event), Payload: comment},
	)

	if err != nil {
		log.Println("Warning: failed to publish post creation event to NATS:", err)
	}

	return object, nil
}

// CreateLike is the resolver for the createLike field.
func (r *mutationResolver) CreateLike(ctx context.Context, input models.LikeInput) (bool, error) {
	personaId, err := getPersonaIdFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("unauthenticated: %w", err)
	}
	// Authorize and route against the target's stored channel and type,
	// never the client's owner/targetType input.
	target, err := r.loadObject(ctx, input.TargetID)
	if err != nil {
		return false, err
	}
	if err := r.authorizeOwner(ctx, target.Owner, personaId, true); err != nil {
		return false, err
	}
	owner := target.Owner

	q := r.Queries
	isLikedByUser, err := q.IsUserLikedTarget(ctx, db.IsUserLikedTargetParams{
		TargetID: input.TargetID,
		ActorID:  int64(personaId),
	})

	if err != nil {
		return false, fmt.Errorf("failed to check if user liked target: %w", err)
	}

	// No change in like status
	if isLikedByUser && input.Liked {
		return true, nil
	}

	// User wants to unlike but hasn't liked before
	if !isLikedByUser && !input.Liked {
		return false, nil
	}

	var action db.EventActionEnum

	if isLikedByUser && !input.Liked {
		action = db.EventActionEnumDelete
	} else if !isLikedByUser && input.Liked {
		action = db.EventActionEnumCreate
	}

	event := db.CreateEventParams{
		Name:       db.EventEnumLike,
		Action:     action,
		TargetID:   input.TargetID,
		TargetType: eventTargetType(target.Type),
		Owner:      db.OwnerEnum(owner.Type),
		OwnerID:    owner.ID,
		ActorID:    int64(personaId),
		ObjectID:   input.TargetID,
	}

	switch action {
	case db.EventActionEnumDelete:
		err = q.UnlikeEvent(ctx, db.UnlikeEventParams{
			TargetID: input.TargetID,
			ActorID:  int64(personaId),
		})
		if err != nil {
			return false, fmt.Errorf("failed to unlike event: %w", err)
		}
	case db.EventActionEnumCreate:
		_, err = q.CreateEvent(ctx, event)
		if err != nil {
			return false, fmt.Errorf("failed to create like event: %w", err)
		}
	}

	var streamName = nats.CONTENT_EVENTS_STREAM

	subjectHelper := subject.New(&streamName, owner, string(db.EventEnumLike), string(action))

	// The like is already stored; a failed publish only delays the counter
	// until the next event on this target or the cache TTL.
	if err := r.NATS.PublishMessage(
		ctx,
		subjectHelper.GetSubject(),
		&nats.MessageType{Event: *models.EventMapper(event), Payload: nil},
	); err != nil {
		log.Println("Warning: failed to publish like event to NATS:", err)
	}

	return true, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	if err := r.deleteObject(ctx, id, models.PostTypePost); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	if err := r.deleteObject(ctx, id, models.PostTypeComment); err != nil {
		return false, err
	}
	return true, nil
}

// GetPosts is the resolver for the getPosts field.
func (r *queryResolver) GetPosts(ctx context.Context, owner models.OwnerInput, ids []string, limit *int32, offset *int32) ([]*models.Post, error) {
	personaId, err := getPersonaIdFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated: %w", err)
	}
	if err := r.authorizeOwner(ctx, &models.Owner{ID: owner.ID, Type: owner.Type}, personaId, false); err != nil {
		return nil, err
	}
	posts, err := getPosts(ctx, models.Owner{
		ID:   owner.ID,
		Type: owner.Type,
	}, &ids, r, *limit, *offset)
	if err != nil {
		return nil, fmt.Errorf("failed to get posts: %w", err)
	}
	return posts, nil
}

// GetComments is the resolver for the getComments field.
func (r *queryResolver) GetComments(ctx context.Context, parentID string, limit *int32, offset *int32) ([]*models.Comment, error) {
	personaId, err := getPersonaIdFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated: %w", err)
	}
	parent, err := r.loadObject(ctx, parentID)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeOwner(ctx, parent.Owner, personaId, false); err != nil {
		return nil, err
	}
	comments, err := getComments(ctx, parentID, r, *limit, *offset)
	if err != nil {
		return nil, fmt.Errorf("failed to get comments: %w", err)
	}
	return comments, nil
}

// GetChannel is the resolver for the getChannel field.
func (r *queryResolver) GetChannel(ctx context.Context, id int64) (*models.Channel, error) {
	personaId, err := getPersonaIdFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated: %w", err)
	}

	// Every persona may see a channel's metadata (so it can ask to join a
	// private one); posts are only fetched for personas that can read them.
	channelAccess, err := access.LoadChannel(ctx, r.Queries, id, personaId)
	if err != nil {
		return nil, err
	}
	canRead := channelAccess.CanRead()

	var channel db.GetChannelRow
	var channelErr, postsErr error
	var posts []*models.Post
	var ownerPersona models.Persona
	var totalPostsCount int32
	wg := sync.WaitGroup{}

	// --- Fetch Channel Details + Owner ---
	wg.Add(1)
	go func() {
		defer wg.Done()
		q := r.Queries
		ctxTimeout, cancel := context.WithTimeout(ctx, 5*time.Second)
		defer cancel()

		channelResult, err := q.GetChannel(ctxTimeout, db.GetChannelParams{
			ID:      id,
			OwnerID: personaId,
		})
		if err != nil {
			channelErr = err
			return
		}
		channel = channelResult

		// Owner lookup + cache
		cachedPersona, err := r.resolvePersonaCached(ctx, channel.OwnerID)
		if err != nil {
			channelErr = err
			return
		}
		ownerPersona = *cachedPersona
	}()

	if canRead {
		// --- Fetch Posts ---
		wg.Add(1)
		go func() {
			defer wg.Done()
			posts, postsErr = getPosts(ctx, models.Owner{
				ID:   id,
				Type: models.OwnerTypeChannel,
			}, nil, r, 10, 0)
		}()

		// --- Fetch Total Posts Count ---
		wg.Add(1)
		go func() {
			defer wg.Done()
			ctxTimeout, cancel := context.WithTimeout(ctx, 5*time.Second)
			defer cancel()

			count, err := getTotalPostsCountForChannel(ctxTimeout, id, r)
			if err != nil {
				log.Println("Warning: failed to get total posts count for channel:", err)
				return
			}
			totalPostsCount = int32(count)
		}()
	}

	wg.Wait()

	if channelErr != nil {
		return nil, channelErr
	}
	if postsErr != nil {
		return nil, postsErr
	}
	if posts == nil {
		posts = []*models.Post{}
	}

	return &models.Channel{
		ID:             channel.ID,
		Name:           channel.Name,
		Description:    &channel.Description,
		BannerImageURL: &channel.Banner,
		ThumbnailURL:   &channel.Thumbnail,
		CreatedAt:      channel.CreatedAt.Time,
		UpdatedAt:      channel.UpdatedAt.Time,
		Posts:          posts,
		TotalPosts:     totalPostsCount,
		Owner:          &ownerPersona,
		IsMember:       channel.IsMember,
		IsFollower:     channel.IsFollower,
		CanModerate:    channelAccess.CanModerate,
	}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
